<?php

namespace Database\Seeders;

use App\Models\Settings\ModuleSetting;
use App\Models\Settings\ModuleStatus;
use App\Services\Settings\ModuleRegistry;
use Illuminate\Database\Seeder;

class ModuleSettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // 1. Seed module statuses
        foreach (ModuleRegistry::all() as $moduleId => $module) {
            ModuleStatus::firstOrCreate(
                ['module' => $moduleId],
                [
                    'is_enabled' => true,
                    'disabled_reason' => null,
                    'disabled_at' => null,
                    'metadata' => [
                        'name' => $module['name'],
                        'category' => $module['category'],
                        'version' => $module['version'],
                    ],
                ]
            );
        }

        // 2. Comprehensive settings specifications
        $settings = [
            // ==========================================
            // 1. COMMERCE SETTINGS
            // ==========================================
            // Availability
            [
                'module' => 'commerce',
                'group' => 'availability',
                'key' => 'stock_visibility',
                'value' => 'show_availability',
                'value_type' => 'select',
                'default_value' => 'show_availability',
                'description' => 'Stock inventory display mode on public storefront and product pages (show_exact, show_availability, hide).',
                'validation_rules' => 'required|in:show_exact,show_availability,hide',
                'sort_order' => 10,
                'is_enabled' => true,
                'is_public' => true,
            ],
            [
                'module' => 'commerce',
                'group' => 'availability',
                'key' => 'customer_stock_visibility',
                'value' => 'in_stock_badge_only',
                'value_type' => 'select',
                'default_value' => 'in_stock_badge_only',
                'description' => 'Legacy alias: stock badge visibility on storefront.',
                'validation_rules' => 'required|string',
                'sort_order' => 11,
                'is_enabled' => true,
                'is_public' => true,
            ],
            [
                'module' => 'commerce',
                'group' => 'availability',
                'key' => 'allow_backorders',
                'value' => '0',
                'value_type' => 'boolean',
                'default_value' => '0',
                'description' => 'Permit shoppers to checkout items even when on-hand inventory is zero.',
                'validation_rules' => 'required|boolean',
                'sort_order' => 20,
                'is_enabled' => true,
                'is_public' => false,
            ],
            [
                'module' => 'commerce',
                'group' => 'availability',
                'key' => 'out_of_stock_behavior',
                'value' => 'show_unavailable',
                'value_type' => 'select',
                'default_value' => 'show_unavailable',
                'description' => 'Catalog display behavior for out-of-stock garments (hide, show_unavailable, allow_backorder).',
                'validation_rules' => 'required|in:hide,show_unavailable,allow_backorder',
                'sort_order' => 30,
                'is_enabled' => true,
                'is_public' => true,
            ],
            [
                'module' => 'commerce',
                'group' => 'availability',
                'key' => 'enable_preorders',
                'value' => '1',
                'value_type' => 'boolean',
                'default_value' => '1',
                'description' => 'Allow customers to preorder artisan garments currently in Kathmandu loom production.',
                'validation_rules' => 'required|boolean',
                'sort_order' => 40,
                'is_enabled' => true,
            ],
            [
                'module' => 'commerce',
                'group' => 'availability',
                'key' => 'preorder_deposit_percentage',
                'value' => '100',
                'value_type' => 'percentage',
                'default_value' => '100',
                'description' => 'Deposit percentage charged at checkout for pre-order reservations.',
                'validation_rules' => 'required|numeric|min:10|max:100',
                'sort_order' => 50,
                'is_enabled' => true,
            ],
            [
                'module' => 'commerce',
                'group' => 'availability',
                'key' => 'new_arrival_threshold_days',
                'value' => '60',
                'value_type' => 'integer',
                'default_value' => '60',
                'description' => 'Garments created within this number of elapsed days are automatically badged as New Arrivals.',
                'validation_rules' => 'required|integer|min:1|max:365',
                'sort_order' => 60,
                'is_enabled' => true,
            ],
            [
                'module' => 'commerce',
                'group' => 'availability',
                'key' => 'default_preorder_dispatch_note',
                'value' => '15–20 business days',
                'value_type' => 'string',
                'default_value' => '15–20 business days',
                'description' => 'Default expected dispatch lead time communicated to customers on preorder reservations.',
                'validation_rules' => 'required|string|max:100',
                'sort_order' => 70,
                'is_enabled' => true,
            ],

            // Checkout
            [
                'module' => 'commerce',
                'group' => 'checkout',
                'key' => 'reservation_ttl_minutes',
                'value' => '30',
                'value_type' => 'duration',
                'default_value' => '30',
                'description' => 'Minutes reserved items are held in checkout before returning to the public stock pool.',
                'validation_rules' => 'required|integer|min:5|max:180',
                'sort_order' => 10,
                'is_enabled' => true,
            ],
            [
                'module' => 'commerce',
                'group' => 'checkout',
                'key' => 'allow_guest_checkout',
                'value' => '1',
                'value_type' => 'boolean',
                'default_value' => '1',
                'description' => 'Permit shoppers to complete orders without mandatory account registration.',
                'validation_rules' => 'required|boolean',
                'sort_order' => 20,
                'is_enabled' => true,
            ],
            [
                'module' => 'commerce',
                'group' => 'checkout',
                'key' => 'guest_checkout_allowed',
                'value' => '1',
                'value_type' => 'boolean',
                'default_value' => '1',
                'description' => 'Legacy alias: guest checkout allowed.',
                'validation_rules' => 'required|boolean',
                'sort_order' => 21,
                'is_enabled' => true,
            ],
            [
                'module' => 'commerce',
                'group' => 'checkout',
                'key' => 'minimum_order_value_npr',
                'value' => '0.00',
                'value_type' => 'currency',
                'default_value' => '0.00',
                'description' => 'Minimum cart subtotal in npr required to proceed to payment.',
                'validation_rules' => 'required|numeric|min:0',
                'sort_order' => 30,
                'is_enabled' => true,
            ],
            [
                'module' => 'commerce',
                'group' => 'checkout',
                'key' => 'minimum_order_value_npr',
                'value' => '0.00',
                'value_type' => 'currency',
                'default_value' => '0.00',
                'description' => 'Minimum cart subtotal in npr required to proceed to payment.',
                'validation_rules' => 'required|numeric|min:0',
                'sort_order' => 40,
                'is_enabled' => true,
            ],
            [
                'module' => 'commerce',
                'group' => 'checkout',
                'key' => 'checkout_session_lifetime_minutes',
                'value' => '60',
                'value_type' => 'duration',
                'default_value' => '60',
                'description' => 'Online checkout session expiration timeout in minutes.',
                'validation_rules' => 'required|integer|min:15|max:1440',
                'sort_order' => 50,
                'is_enabled' => true,
            ],

            // Ordering
            [
                'module' => 'commerce',
                'group' => 'ordering',
                'key' => 'order_cancellation_window_minutes',
                'value' => '60',
                'value_type' => 'duration',
                'default_value' => '60',
                'description' => 'Minutes after order placement during which customers may self-cancel before fulfillment.',
                'validation_rules' => 'required|integer|min:0|max:1440',
                'sort_order' => 10,
                'is_enabled' => true,
            ],
            [
                'module' => 'commerce',
                'group' => 'ordering',
                'key' => 'cancellation_window_minutes',
                'value' => '60',
                'value_type' => 'duration',
                'default_value' => '60',
                'description' => 'Alias: Order cancellation window minutes.',
                'validation_rules' => 'required|integer|min:0|max:1440',
                'sort_order' => 11,
                'is_enabled' => true,
            ],
            [
                'module' => 'commerce',
                'group' => 'ordering',
                'key' => 'order_prefix',
                'value' => 'LJ-',
                'value_type' => 'string',
                'default_value' => 'LJ-',
                'description' => 'Standard prefix prepended to customer order sequence numbers.',
                'validation_rules' => 'required|string|max:10',
                'sort_order' => 20,
                'is_enabled' => true,
            ],
            [
                'module' => 'commerce',
                'group' => 'ordering',
                'key' => 'auto_send_order_confirmation',
                'value' => '1',
                'value_type' => 'boolean',
                'default_value' => '1',
                'description' => 'Automatically dispatch order confirmation email upon verified payment.',
                'validation_rules' => 'required|boolean',
                'sort_order' => 30,
                'is_enabled' => true,
            ],

            [
                'module' => 'commerce',
                'group' => 'ordering',
                'key' => 'order_confirmation_email',
                'value' => '1',
                'value_type' => 'boolean',
                'default_value' => '1',
                'description' => 'Legacy alias: Automatically send branded transactional invoice upon payment.',
                'validation_rules' => 'required|boolean',
                'sort_order' => 31,
                'is_enabled' => true,
            ],

            // Promotions
            [
                'module' => 'commerce',
                'group' => 'promotions',
                'key' => 'enable_promotions',
                'value' => '1',
                'value_type' => 'boolean',
                'default_value' => '1',
                'description' => 'Enable coupon code input and promotional campaign validation at checkout.',
                'validation_rules' => 'required|boolean',
                'sort_order' => 10,
                'is_enabled' => true,
            ],
            [
                'module' => 'commerce',
                'group' => 'promotions',
                'key' => 'max_discount_percentage',
                'value' => '30.00',
                'value_type' => 'percentage',
                'default_value' => '30.00',
                'description' => 'Maximum allowable total discount percentage applicable to cart subtotal.',
                'validation_rules' => 'required|numeric|min:0|max:100',
                'sort_order' => 20,
                'is_enabled' => true,
            ],
            [
                'module' => 'commerce',
                'group' => 'promotions',
                'key' => 'allow_coupon_stacking',
                'value' => '0',
                'value_type' => 'boolean',
                'default_value' => '0',
                'description' => 'Allow shoppers to apply multiple discount codes to a single order.',
                'validation_rules' => 'required|boolean',
                'sort_order' => 30,
                'is_enabled' => true,
            ],
            [
                'module' => 'commerce',
                'group' => 'promotions',
                'key' => 'max_coupons_per_order',
                'value' => '1',
                'value_type' => 'integer',
                'default_value' => '1',
                'description' => 'Maximum coupon codes that can be applied to a single cart.',
                'validation_rules' => 'required|integer|min:1|max:5',
                'sort_order' => 40,
                'is_enabled' => true,
            ],
            [
                'module' => 'commerce',
                'group' => 'promotions',
                'key' => 'min_cart_amount_for_promotions',
                'value' => '0.00',
                'value_type' => 'currency',
                'default_value' => '0.00',
                'description' => 'Minimum order subtotal threshold before promotional discounts activate.',
                'validation_rules' => 'required|numeric|min:0',
                'sort_order' => 50,
                'is_enabled' => true,
            ],

            // Returns
            [
                'module' => 'commerce',
                'group' => 'returns',
                'key' => 'return_window_days',
                'value' => '14',
                'value_type' => 'integer',
                'default_value' => '14',
                'description' => 'Permitted return window in days after order delivery date.',
                'validation_rules' => 'required|integer|min:0|max:90',
                'sort_order' => 10,
                'is_enabled' => true,
            ],
            [
                'module' => 'commerce',
                'group' => 'returns',
                'key' => 'auto_restock_on_refund',
                'value' => '1',
                'value_type' => 'boolean',
                'default_value' => '1',
                'description' => 'Automatically return approved returned items to active sellable inventory.',
                'validation_rules' => 'required|boolean',
                'sort_order' => 20,
                'is_enabled' => true,
            ],
            [
                'module' => 'commerce',
                'group' => 'returns',
                'key' => 'restocking_fee_percentage',
                'value' => '0.00',
                'value_type' => 'percentage',
                'default_value' => '0.00',
                'description' => 'Percentage deducted from refund total for processing customer returns.',
                'validation_rules' => 'required|numeric|min:0|max:50',
                'sort_order' => 30,
                'is_enabled' => true,
            ],

            // ==========================================
            // 2. INVENTORY SETTINGS
            // ==========================================
            [
                'module' => 'inventory',
                'group' => 'general',
                'key' => 'default_warehouse_code',
                'value' => 'WH-KTM-MAIN',
                'value_type' => 'string',
                'default_value' => 'WH-KTM-MAIN',
                'description' => 'Primary distribution warehouse used for online order fulfillment.',
                'validation_rules' => 'required|string|max:50',
                'sort_order' => 10,
                'is_enabled' => true,
            ],
            [
                'module' => 'inventory',
                'group' => 'general',
                'key' => 'negative_stock_policy',
                'value' => 'strictly_forbidden',
                'value_type' => 'select',
                'default_value' => 'strictly_forbidden',
                'description' => 'Ledger constraint governing whether physical inventory balance can ever drop below 0.',
                'validation_rules' => 'required|in:strictly_forbidden,warning_only',
                'options' => ['strictly_forbidden' => 'Strictly Forbidden (Reject Mutation)', 'warning_only' => 'Warning Only (Allow Overselling)'],
                'sort_order' => 20,
                'is_enabled' => true,
            ],
            [
                'module' => 'inventory',
                'group' => 'general',
                'key' => 'require_warehouse_on_mutations',
                'value' => '1',
                'value_type' => 'boolean',
                'default_value' => '1',
                'description' => 'Mandate explicit location routing on every stock mutation.',
                'validation_rules' => 'required|boolean',
                'sort_order' => 30,
                'is_enabled' => true,
            ],
            [
                'module' => 'inventory',
                'group' => 'reservations',
                'key' => 'enable_reservations',
                'value' => '1',
                'value_type' => 'boolean',
                'default_value' => '1',
                'description' => 'Hold available stock during customer checkout sessions to prevent race-condition overselling.',
                'validation_rules' => 'required|boolean',
                'sort_order' => 10,
                'is_enabled' => true,
            ],
            [
                'module' => 'inventory',
                'group' => 'reservations',
                'key' => 'reservation_ttl_minutes',
                'value' => '30',
                'value_type' => 'duration',
                'default_value' => '30',
                'description' => 'Duration in minutes a cart reservation holds physical stock before auto-release.',
                'validation_rules' => 'required|integer|min:5|max:120',
                'sort_order' => 20,
                'is_enabled' => true,
            ],
            [
                'module' => 'inventory',
                'group' => 'reservations',
                'key' => 'auto_expire_reservations',
                'value' => '1',
                'value_type' => 'boolean',
                'default_value' => '1',
                'description' => 'Background daemon automatically releases expired cart reservations.',
                'validation_rules' => 'required|boolean',
                'sort_order' => 30,
                'is_enabled' => true,
            ],
            [
                'module' => 'inventory',
                'group' => 'stock_control',
                'key' => 'low_stock_alerts_enabled',
                'value' => '1',
                'value_type' => 'boolean',
                'default_value' => '1',
                'description' => 'Trigger administrative notifications when stock reaches or breaches reorder threshold.',
                'validation_rules' => 'required|boolean',
                'sort_order' => 10,
                'is_enabled' => true,
            ],
            [
                'module' => 'inventory',
                'group' => 'stock_control',
                'key' => 'default_reorder_point',
                'value' => '3',
                'value_type' => 'integer',
                'default_value' => '3',
                'description' => 'Default quantity threshold that triggers procurement replenishment recommendations.',
                'validation_rules' => 'required|integer|min:0|max:100',
                'sort_order' => 20,
                'is_enabled' => true,
            ],
            [
                'module' => 'inventory',
                'group' => 'stock_control',
                'key' => 'default_safety_stock',
                'value' => '2',
                'value_type' => 'integer',
                'default_value' => '2',
                'description' => 'Emergency buffer stock held in reserve across multi-channel distribution.',
                'validation_rules' => 'required|integer|min:0|max:50',
                'sort_order' => 30,
                'is_enabled' => true,
            ],
            [
                'module' => 'inventory',
                'group' => 'stock_control',
                'key' => 'require_adjustment_approval',
                'value' => '1',
                'value_type' => 'boolean',
                'default_value' => '1',
                'description' => 'Manual damage and loss adjustments require supervisory sign-off before posting.',
                'validation_rules' => 'required|boolean',
                'sort_order' => 40,
                'is_enabled' => true,
            ],
            [
                'module' => 'inventory',
                'group' => 'transfers',
                'key' => 'require_dispatch_confirmation',
                'value' => '1',
                'value_type' => 'boolean',
                'default_value' => '1',
                'description' => 'Origin warehouse must mark transfer dispatched before goods are placed in transit.',
                'validation_rules' => 'required|boolean',
                'sort_order' => 10,
                'is_enabled' => true,
            ],
            [
                'module' => 'inventory',
                'group' => 'transfers',
                'key' => 'require_receiving_confirmation',
                'value' => '1',
                'value_type' => 'boolean',
                'default_value' => '1',
                'description' => 'Destination facility must explicitly count and receive incoming transfer parcels.',
                'validation_rules' => 'required|boolean',
                'sort_order' => 20,
                'is_enabled' => true,
            ],
            [
                'module' => 'inventory',
                'group' => 'returns',
                'key' => 'require_return_inspection',
                'value' => '1',
                'value_type' => 'boolean',
                'default_value' => '1',
                'description' => 'All returned items must undergo QC inspection before physical stock restoration.',
                'validation_rules' => 'required|boolean',
                'sort_order' => 10,
                'is_enabled' => true,
            ],
            [
                'module' => 'inventory',
                'group' => 'returns',
                'key' => 'default_return_disposition',
                'value' => 'quarantine',
                'value_type' => 'select',
                'default_value' => 'quarantine',
                'description' => 'Initial holding state for customer returns before inspection.',
                'validation_rules' => 'required|in:quarantine,restock_available,damaged',
                'options' => ['quarantine' => 'Quarantine (QC Hold)', 'restock_available' => 'Direct to Available Stock', 'damaged' => 'Mark as Damaged / Write-off'],
                'sort_order' => 20,
                'is_enabled' => true,
            ],
            [
                'module' => 'inventory',
                'group' => 'valuation',
                'key' => 'valuation_method',
                'value' => 'fifo',
                'value_type' => 'select',
                'default_value' => 'fifo',
                'description' => 'Inventory asset valuation standard under Årsregnskabsloven § 38.',
                'validation_rules' => 'required|in:fifo,weighted_average,specific_identification',
                'options' => ['fifo' => 'FIFO (First-In, First-Out)', 'weighted_average' => 'Weighted Average Landed Cost', 'specific_identification' => 'Specific Identification (By Batch/Piece)'],
                'sort_order' => 10,
                'is_enabled' => true,
            ],
            [
                'module' => 'inventory',
                'group' => 'valuation',
                'key' => 'include_freight_in_landed_cost',
                'value' => '1',
                'value_type' => 'boolean',
                'default_value' => '1',
                'description' => 'Capitalize inbound international freight and customs duty into inventory asset value.',
                'validation_rules' => 'required|boolean',
                'sort_order' => 20,
                'is_enabled' => true,
            ],
            [
                'module' => 'inventory',
                'group' => 'transfers_adjustments',
                'key' => 'stock_transfer_prefix',
                'value' => 'TRF-',
                'value_type' => 'string',
                'default_value' => 'TRF-',
                'description' => 'Prefix assigned to sequential inter-warehouse stock transfer consignments.',
                'validation_rules' => 'required|string|max:10',
                'sort_order' => 30,
                'is_enabled' => true,
            ],
            [
                'module' => 'inventory',
                'group' => 'transfers_adjustments',
                'key' => 'stock_adjustment_prefix',
                'value' => 'ADJ-',
                'value_type' => 'string',
                'default_value' => 'ADJ-',
                'description' => 'Prefix assigned to sequential stock write-offs and cycle count adjustment vouchers.',
                'validation_rules' => 'required|string|max:10',
                'sort_order' => 40,
                'is_enabled' => true,
            ],

            // ==========================================
            // 3. PURCHASING SETTINGS
            // ==========================================
            [
                'module' => 'purchasing',
                'group' => 'approvals',
                'key' => 'po_approval_required',
                'value' => '1',
                'value_type' => 'boolean',
                'default_value' => '1',
                'description' => 'Supplier purchase orders require formal managerial approval before transmission.',
                'validation_rules' => 'required|boolean',
                'sort_order' => 10,
                'is_enabled' => true,
            ],
            [
                'module' => 'purchasing',
                'group' => 'approvals',
                'key' => 'require_po_approval',
                'value' => '1',
                'value_type' => 'boolean',
                'default_value' => '1',
                'description' => 'Legacy alias: Supplier purchase orders require formal managerial approval.',
                'validation_rules' => 'required|boolean',
                'sort_order' => 11,
                'is_enabled' => true,
            ],
            [
                'module' => 'purchasing',
                'group' => 'approvals',
                'key' => 'po_approval_threshold_npr',
                'value' => '10000.00',
                'value_type' => 'currency',
                'default_value' => '10000.00',
                'description' => 'Purchase order total value above which executive dual sign-off is mandated.',
                'validation_rules' => 'required|numeric|min:0',
                'sort_order' => 20,
                'is_enabled' => true,
            ],
            [
                'module' => 'purchasing',
                'group' => 'approvals',
                'key' => 'approval_roles',
                'value' => 'super_admin,admin,workspace_admin',
                'value_type' => 'string',
                'default_value' => 'super_admin,admin,workspace_admin',
                'description' => 'Comma-separated administrative security roles authorized to sign off high-value POs.',
                'validation_rules' => 'required|string|max:255',
                'sort_order' => 25,
                'is_enabled' => true,
            ],
            [
                'module' => 'purchasing',
                'group' => 'approvals',
                'key' => 'approval_escalation_days',
                'value' => '3',
                'value_type' => 'integer',
                'default_value' => '3',
                'description' => 'Days pending in submitted status before triggering managerial escalation.',
                'validation_rules' => 'required|integer|min:1|max:90',
                'sort_order' => 30,
                'is_enabled' => true,
            ],
            [
                'module' => 'purchasing',
                'group' => 'approvals',
                'key' => 'approval_expiry_days',
                'value' => '14',
                'value_type' => 'integer',
                'default_value' => '14',
                'description' => 'Days unapproved purchase orders remain open before expiration.',
                'validation_rules' => 'required|integer|min:1|max:365',
                'sort_order' => 40,
                'is_enabled' => true,
            ],
            [
                'module' => 'purchasing',
                'group' => 'approvals',
                'key' => 'rejection_behavior',
                'value' => 'rejected',
                'value_type' => 'select',
                'default_value' => 'rejected',
                'description' => 'State transition applied when a purchase order is rejected (rejected, draft, cancelled).',
                'validation_rules' => 'required|in:rejected,draft,cancelled',
                'sort_order' => 50,
                'is_enabled' => true,
            ],
            [
                'module' => 'purchasing',
                'group' => 'approvals',
                'key' => 'auto_po_numbering_prefix',
                'value' => 'PO-',
                'value_type' => 'string',
                'default_value' => 'PO-',
                'description' => 'Prefix format for purchase order documents.',
                'validation_rules' => 'required|string|max:10',
                'sort_order' => 60,
                'is_enabled' => true,
            ],
            [
                'module' => 'purchasing',
                'group' => 'receiving',
                'key' => 'allow_partial_receiving',
                'value' => '1',
                'value_type' => 'boolean',
                'default_value' => '1',
                'description' => 'Allow warehouse staff to receive shipments in staggered consignments.',
                'validation_rules' => 'required|boolean',
                'sort_order' => 10,
                'is_enabled' => true,
            ],
            [
                'module' => 'purchasing',
                'group' => 'receiving',
                'key' => 'receiving_tolerance_percentage',
                'value' => '5.00',
                'value_type' => 'percentage',
                'default_value' => '5.00',
                'description' => 'Allowable over-delivery variance without requiring revised purchase requisition.',
                'validation_rules' => 'required|numeric|min:0|max:50',
                'sort_order' => 20,
                'is_enabled' => true,
            ],
            [
                'module' => 'purchasing',
                'group' => 'receiving',
                'key' => 'over_receipt_handling',
                'value' => 'reject',
                'value_type' => 'select',
                'default_value' => 'reject',
                'description' => 'Enforcement policy when received quantity exceeds allowable tolerance (reject, warn).',
                'validation_rules' => 'required|in:reject,warn',
                'sort_order' => 30,
                'is_enabled' => true,
            ],
            [
                'module' => 'purchasing',
                'group' => 'receiving',
                'key' => 'short_receipt_handling',
                'value' => 'allow_partial',
                'value_type' => 'select',
                'default_value' => 'allow_partial',
                'description' => 'Action taken when incoming delivery is short (allow_partial, close_order).',
                'validation_rules' => 'required|in:allow_partial,close_order',
                'sort_order' => 40,
                'is_enabled' => true,
            ],
            [
                'module' => 'purchasing',
                'group' => 'receiving',
                'key' => 'receiving_confirmation_requirements',
                'value' => 'standard',
                'value_type' => 'select',
                'default_value' => 'standard',
                'description' => 'Mandatory verification level prior to finalizing warehouse goods receipt.',
                'validation_rules' => 'required|in:standard,require_delivery_note',
                'sort_order' => 50,
                'is_enabled' => true,
            ],
            [
                'module' => 'purchasing',
                'group' => 'suppliers',
                'key' => 'default_payment_terms',
                'value' => 'net_30',
                'value_type' => 'select',
                'default_value' => 'net_30',
                'description' => 'Default commercial payment terms for new purchase orders.',
                'validation_rules' => 'required|in:net_14,net_30,net_60,cod',
                'sort_order' => 10,
                'is_enabled' => true,
            ],
            [
                'module' => 'purchasing',
                'group' => 'suppliers',
                'key' => 'default_lead_time_days',
                'value' => '14',
                'value_type' => 'integer',
                'default_value' => '14',
                'description' => 'Default expected lead time in days between order date and warehouse arrival.',
                'validation_rules' => 'required|integer|min:1|max:180',
                'sort_order' => 20,
                'is_enabled' => true,
            ],
            [
                'module' => 'purchasing',
                'group' => 'suppliers',
                'key' => 'default_currency',
                'value' => 'NPR',
                'value_type' => 'select',
                'default_value' => 'NPR',
                'description' => 'Default currency for artisan and supplier purchase orders (Nepalese Rupees).',
                'validation_rules' => 'required|string|max:5',
                'sort_order' => 30,
                'is_enabled' => true,
            ],
            [
                'module' => 'purchasing',
                'group' => 'suppliers',
                'key' => 'enforce_active_supplier',
                'value' => '1',
                'value_type' => 'boolean',
                'default_value' => '1',
                'description' => 'Block creation and approval of purchase orders for deactivated or suspended suppliers.',
                'validation_rules' => 'required|boolean',
                'sort_order' => 40,
                'is_enabled' => true,
            ],

            // ==========================================
            // 4. POS SETTINGS
            // ==========================================
            [
                'module' => 'pos',
                'group' => 'register',
                'key' => 'offline_sales_enabled',
                'value' => '1',
                'value_type' => 'boolean',
                'default_value' => '1',
                'description' => 'Enable showroom and pop-up store staff to process walk-in customer offline sales.',
                'validation_rules' => 'required|boolean',
                'sort_order' => 5,
                'is_enabled' => true,
            ],
            [
                'module' => 'pos',
                'group' => 'register',
                'key' => 'default_pos_showroom_code',
                'value' => 'STORE-KTM-01',
                'value_type' => 'string',
                'default_value' => 'STORE-KTM-01',
                'description' => 'Default warehouse location code mapped to physical in-store POS transactions.',
                'validation_rules' => 'required|string|max:50',
                'sort_order' => 10,
                'is_enabled' => true,
            ],
            [
                'module' => 'pos',
                'group' => 'register',
                'key' => 'require_cash_drawer_count',
                'value' => '1',
                'value_type' => 'boolean',
                'default_value' => '1',
                'description' => 'Mandate opening and closing physical cash drawer audits per shift.',
                'validation_rules' => 'required|boolean',
                'sort_order' => 20,
                'is_enabled' => true,
            ],
            [
                'module' => 'pos',
                'group' => 'register',
                'key' => 'max_pos_discount_percentage',
                'value' => '20.00',
                'value_type' => 'percentage',
                'default_value' => '20.00',
                'description' => 'Maximum courtesy discount a sales associate may grant without manager override.',
                'validation_rules' => 'required|numeric|min:0|max:100',
                'sort_order' => 30,
                'is_enabled' => true,
            ],
            [
                'module' => 'pos',
                'group' => 'receipts_hardware',
                'key' => 'receipt_prefix',
                'value' => 'OFF-',
                'value_type' => 'string',
                'default_value' => 'OFF-',
                'description' => 'Sequential receipt numbering prefix for physical register printouts (e.g. OFF-000001).',
                'validation_rules' => 'required|string|max:15',
                'sort_order' => 10,
                'is_enabled' => true,
            ],
            [
                'module' => 'pos',
                'group' => 'receipts_hardware',
                'key' => 'auto_pos_inventory_deduction',
                'value' => '1',
                'value_type' => 'boolean',
                'default_value' => '1',
                'description' => 'Instantly deduct showroom stock from inventory engine upon receipt completion.',
                'validation_rules' => 'required|boolean',
                'sort_order' => 20,
                'is_enabled' => true,
            ],

            // ==========================================
            // 5. ACCOUNTING & FISCAL CONTROLS SETTINGS
            // ==========================================
            // Group: Fiscal Controls & Period Governance
            [
                'module' => 'accounting',
                'group' => 'fiscal_controls',
                'key' => 'fiscal_year_start_month',
                'value' => '1',
                'value_type' => 'integer',
                'default_value' => '1',
                'description' => 'Calendar month when financial year opens (1 = January / Nepali Shrawan mapped).',
                'validation_rules' => 'required|integer|min:1|max:12',
                'sort_order' => 10,
                'is_enabled' => true,
            ],
            [
                'module' => 'accounting',
                'group' => 'fiscal_controls',
                'key' => 'default_accounting_period',
                'value' => 'monthly',
                'value_type' => 'select',
                'default_value' => 'monthly',
                'description' => 'Frequency of financial statement closings under Nepal Accounting Standards (NAS).',
                'validation_rules' => 'required|in:monthly,quarterly,annual',
                'options' => ['monthly' => 'Monthly Closings', 'quarterly' => 'Quarterly Closings', 'annual' => 'Annual Only'],
                'sort_order' => 20,
                'is_enabled' => true,
            ],
            [
                'module' => 'accounting',
                'group' => 'fiscal_controls',
                'key' => 'allow_backdated_postings',
                'value' => '1',
                'value_type' => 'boolean',
                'default_value' => '1',
                'description' => 'Controls whether transactions can be posted to historical closed or prior calendar periods.',
                'validation_rules' => 'required|boolean',
                'sort_order' => 30,
                'is_enabled' => true,
            ],
            [
                'module' => 'accounting',
                'group' => 'fiscal_controls',
                'key' => 'max_backdated_days',
                'value' => '30',
                'value_type' => 'integer',
                'default_value' => '30',
                'description' => 'Maximum elapsed days into the past a historical transaction can be recorded.',
                'validation_rules' => 'required|integer|min:0|max:365',
                'sort_order' => 40,
                'is_enabled' => true,
            ],
            [
                'module' => 'accounting',
                'group' => 'fiscal_controls',
                'key' => 'lock_periods_on_close',
                'value' => '1',
                'value_type' => 'boolean',
                'default_value' => '1',
                'description' => 'Automatically locks fiscal period upon completion of monthly/annual closing.',
                'validation_rules' => 'required|boolean',
                'sort_order' => 50,
                'is_enabled' => true,
            ],
            [
                'module' => 'accounting',
                'group' => 'fiscal_controls',
                'key' => 'period_reopen_roles',
                'value' => 'admin',
                'value_type' => 'string',
                'default_value' => 'admin',
                'description' => 'Comma-separated user roles authorized to reopen locked or closed accounting periods.',
                'validation_rules' => 'required|string|max:50',
                'sort_order' => 60,
                'is_enabled' => true,
            ],
            [
                'module' => 'accounting',
                'group' => 'fiscal_controls',
                'key' => 'audit_retention_years',
                'value' => '7',
                'value_type' => 'integer',
                'default_value' => '7',
                'description' => 'Statutory audit and tax documentation retention period under Nepal Tax Act (7 years).',
                'validation_rules' => 'required|integer|min:5|max:20',
                'sort_order' => 70,
                'is_enabled' => true,
            ],

            // Group: VAT & Statutory Taxation
            [
                'module' => 'accounting',
                'group' => 'vat_taxation',
                'key' => 'standard_vat_rate',
                'value' => '13.00',
                'value_type' => 'decimal',
                'default_value' => '13.00',
                'description' => 'Standard statutory Nepal VAT rate under Value Added Tax Act, 2052 (13.00%).',
                'validation_rules' => 'required|numeric|min:0|max:100',
                'sort_order' => 10,
                'is_enabled' => true,
            ],
            [
                'module' => 'accounting',
                'group' => 'vat_taxation',
                'key' => 'vat_calculation_mode',
                'value' => 'nepal_single_rate_13',
                'value_type' => 'select',
                'default_value' => 'nepal_single_rate_13',
                'description' => 'VAT calculation engine mode across sales channels (Nepal single 13% statutory rate).',
                'validation_rules' => 'required|in:nepal_single_rate_13,exempt',
                'options' => ['nepal_single_rate_13' => 'Nepal Standard Single Rate 13%', 'exempt' => 'VAT Exempt'],
                'sort_order' => 20,
                'is_enabled' => true,
            ],
            [
                'module' => 'accounting',
                'group' => 'vat_taxation',
                'key' => 'enable_nepal_ird_vat_compliance',
                'value' => '1',
                'value_type' => 'boolean',
                'default_value' => '1',
                'description' => 'Mandatory Nepal Inland Revenue Department (IRD) 13% statutory VAT compliance.',
                'validation_rules' => 'required|boolean',
                'sort_order' => 30,
                'is_enabled' => true,
            ],
            [
                'module' => 'accounting',
                'group' => 'vat_taxation',
                'key' => 'vat_rounding_mode',
                'value' => 'line_round',
                'value_type' => 'select',
                'default_value' => 'line_round',
                'description' => 'VAT rounding precision methodology.',
                'validation_rules' => 'required|in:line_round,invoice_round',
                'options' => ['line_round' => 'Round per Line Item', 'invoice_round' => 'Round on Invoice Total'],
                'sort_order' => 40,
                'is_enabled' => true,
            ],
            [
                'module' => 'accounting',
                'group' => 'vat_taxation',
                'key' => 'vat_reporting_frequency',
                'value' => 'monthly',
                'value_type' => 'select',
                'default_value' => 'monthly',
                'description' => 'Official Nepal IRD Anusuchi 10 VAT return filing cycle (Monthly / मासिक विवरण).',
                'validation_rules' => 'required|in:monthly,quarterly,semi_annual',
                'options' => ['monthly' => 'Monthly (मासिक - 25th of next Nepali month)', 'quarterly' => 'Quarterly', 'semi_annual' => 'Semi-Annual'],
                'sort_order' => 50,
                'is_enabled' => true,
            ],
            [
                'module' => 'accounting',
                'group' => 'vat_taxation',
                'key' => 'gl_sales_vat_account',
                'value' => '2120',
                'value_type' => 'string',
                'default_value' => '2120',
                'description' => 'General Ledger account for Nepal IRD Output VAT (2120 - मूल्य अभिवृद्धि कर दायित्व).',
                'validation_rules' => 'required|string|max:10',
                'sort_order' => 60,
                'is_enabled' => true,
            ],
            [
                'module' => 'accounting',
                'group' => 'vat_taxation',
                'key' => 'gl_purchase_vat_account',
                'value' => '2130',
                'value_type' => 'string',
                'default_value' => '2130',
                'description' => 'General Ledger account for Nepal IRD Input VAT Credit (2130 - मूल्य अभिवृद्धि कर कट्टी दाबी).',
                'validation_rules' => 'required|string|max:10',
                'sort_order' => 70,
                'is_enabled' => true,
            ],
            [
                'module' => 'accounting',
                'group' => 'vat_taxation',
                'key' => 'gl_vat_settlement_account',
                'value' => '2120',
                'value_type' => 'string',
                'default_value' => '2120',
                'description' => 'General Ledger account for Nepal IRD VAT settlement liability.',
                'validation_rules' => 'required|string|max:10',
                'sort_order' => 80,
                'is_enabled' => true,
            ],

            // Group: Inventory & Landed COGS
            [
                'module' => 'accounting',
                'group' => 'inventory_cogs',
                'key' => 'enable_inventory_gl_sync',
                'value' => '1',
                'value_type' => 'boolean',
                'default_value' => '1',
                'description' => 'Automatically synchronize stock mutations into Nepal double-entry General Ledger (Konto 1210 / 5110).',
                'validation_rules' => 'required|boolean',
                'sort_order' => 10,
                'is_enabled' => true,
            ],
            [
                'module' => 'accounting',
                'group' => 'inventory_cogs',
                'key' => 'inventory_valuation_method',
                'value' => 'fifo',
                'value_type' => 'select',
                'default_value' => 'fifo',
                'description' => 'Inventory asset valuation methodology under Nepal Accounting Standards (NAS).',
                'validation_rules' => 'required|in:fifo,weighted_average',
                'options' => ['fifo' => 'First-In, First-Out (FIFO)', 'weighted_average' => 'Weighted Average Cost (WAC)'],
                'sort_order' => 20,
                'is_enabled' => true,
            ],
            [
                'module' => 'accounting',
                'group' => 'inventory_cogs',
                'key' => 'auto_post_cogs_on_fulfillment',
                'value' => '1',
                'value_type' => 'boolean',
                'default_value' => '1',
                'description' => 'Automatically post Cost of Goods Sold expense upon order dispatch and fulfillment.',
                'validation_rules' => 'required|boolean',
                'sort_order' => 30,
                'is_enabled' => true,
            ],
            [
                'module' => 'accounting',
                'group' => 'inventory_cogs',
                'key' => 'gl_inventory_asset_account',
                'value' => '1210',
                'value_type' => 'string',
                'default_value' => '1210',
                'description' => 'General Ledger balance sheet account for Physical Merchandise Inventory (1210 - सञ्चित मालसामान मौज्दात).',
                'validation_rules' => 'required|string|max:10',
                'sort_order' => 40,
                'is_enabled' => true,
            ],
            [
                'module' => 'accounting',
                'group' => 'inventory_cogs',
                'key' => 'gl_cogs_account',
                'value' => '5110',
                'value_type' => 'string',
                'default_value' => '5110',
                'description' => 'General Ledger income statement account for Cost of Goods Sold (5110 - बिक्री भएको मालसामानको लागत).',
                'validation_rules' => 'required|string|max:10',
                'sort_order' => 50,
                'is_enabled' => true,
            ],

            // Group: Sales, Purchasing & Clearing
            [
                'module' => 'accounting',
                'group' => 'sales_purchasing',
                'key' => 'journal_voucher_prefix',
                'value' => 'JV-',
                'value_type' => 'string',
                'default_value' => 'JV-',
                'description' => 'Prefix for double-entry journal vouchers per Nepal Accounting Standards (e.g. JV-2026-0001).',
                'validation_rules' => 'required|string|max:10',
                'sort_order' => 10,
                'is_enabled' => true,
            ],
            [
                'module' => 'accounting',
                'group' => 'sales_purchasing',
                'key' => 'sales_invoice_prefix',
                'value' => 'INV-',
                'value_type' => 'string',
                'default_value' => 'INV-',
                'description' => 'Prefix for customer sales invoices per Nepal IRD regulations (e.g. INV-2026-0001).',
                'validation_rules' => 'required|string|max:10',
                'sort_order' => 20,
                'is_enabled' => true,
            ],
            [
                'module' => 'accounting',
                'group' => 'sales_purchasing',
                'key' => 'credit_note_prefix',
                'value' => 'CN-',
                'value_type' => 'string',
                'default_value' => 'CN-',
                'description' => 'Prefix for sales credit notes and refund vouchers (e.g. CN-2026-0001).',
                'validation_rules' => 'required|string|max:10',
                'sort_order' => 30,
                'is_enabled' => true,
            ],
            [
                'module' => 'accounting',
                'group' => 'sales_purchasing',
                'key' => 'supplier_bill_prefix',
                'value' => 'KH-',
                'value_type' => 'string',
                'default_value' => 'KH-',
                'description' => 'Prefix for Kharid Khata supplier purchase bills (e.g. KH-2026-0001).',
                'validation_rules' => 'required|string|max:10',
                'sort_order' => 40,
                'is_enabled' => true,
            ],
            [
                'module' => 'accounting',
                'group' => 'sales_purchasing',
                'key' => 'gl_accounts_receivable_account',
                'value' => '1150',
                'value_type' => 'string',
                'default_value' => '1150',
                'description' => 'General Ledger account for courier COD and trade receivables (1150 - उठाउनुपर्ने रकम).',
                'validation_rules' => 'required|string|max:10',
                'sort_order' => 50,
                'is_enabled' => true,
            ],
            [
                'module' => 'accounting',
                'group' => 'sales_purchasing',
                'key' => 'gl_accounts_payable_account',
                'value' => '2110',
                'value_type' => 'string',
                'default_value' => '2110',
                'description' => 'General Ledger account for supplier trade payables (2110 - साहु हिसाब / तिर्नुपर्ने रकम).',
                'validation_rules' => 'required|string|max:10',
                'sort_order' => 60,
                'is_enabled' => true,
            ],
            [
                'module' => 'accounting',
                'group' => 'sales_purchasing',
                'key' => 'gl_connectips_clearing_account',
                'value' => '1140',
                'value_type' => 'string',
                'default_value' => '1140',
                'description' => 'General Ledger clearing account for ConnectIPS / online payment gateways.',
                'validation_rules' => 'required|string|max:10',
                'sort_order' => 70,
                'is_enabled' => true,
            ],
            [
                'module' => 'accounting',
                'group' => 'sales_purchasing',
                'key' => 'gl_esewa_clearing_account',
                'value' => '1130',
                'value_type' => 'string',
                'default_value' => '1130',
                'description' => 'General Ledger clearing account for eSewa / digital wallet payments.',
                'validation_rules' => 'required|string|max:10',
                'sort_order' => 80,
                'is_enabled' => true,
            ],

            // Group: Journal Governance & Immutability
            [
                'module' => 'accounting',
                'group' => 'journal_governance',
                'key' => 'enforce_balanced_journals',
                'value' => '1',
                'value_type' => 'boolean',
                'default_value' => '1',
                'description' => 'Strictly enforces sum(debit) == sum(credit) for every posted journal entry under Nepal Accounting Standards.',
                'validation_rules' => 'required|boolean',
                'sort_order' => 10,
                'is_enabled' => true,
            ],
            [
                'module' => 'accounting',
                'group' => 'journal_governance',
                'key' => 'max_journal_line_difference_tolerance',
                'value' => '0.01',
                'value_type' => 'decimal',
                'default_value' => '0.01',
                'description' => 'Maximum permissible fractional rounding variance before rejecting unbalanced voucher.',
                'validation_rules' => 'required|numeric|min:0|max:1',
                'sort_order' => 20,
                'is_enabled' => true,
            ],
            [
                'module' => 'accounting',
                'group' => 'journal_governance',
                'key' => 'manual_journal_roles',
                'value' => 'admin,accountant',
                'value_type' => 'string',
                'default_value' => 'admin,accountant',
                'description' => 'Comma-separated user roles authorized to post manual general journal adjustments.',
                'validation_rules' => 'required|string|max:50',
                'sort_order' => 30,
                'is_enabled' => true,
            ],
            [
                'module' => 'accounting',
                'group' => 'journal_governance',
                'key' => 'require_reversal_reason',
                'value' => '1',
                'value_type' => 'boolean',
                'default_value' => '1',
                'description' => 'Mandates explicit business justification for journal voucher reversals.',
                'validation_rules' => 'required|boolean',
                'sort_order' => 40,
                'is_enabled' => true,
            ],
            [
                'module' => 'accounting',
                'group' => 'journal_governance',
                'key' => 'allow_reversals_in_closed_periods',
                'value' => '0',
                'value_type' => 'boolean',
                'default_value' => '0',
                'description' => 'Whether reversals can be back-posted into closed fiscal periods.',
                'validation_rules' => 'required|boolean',
                'sort_order' => 50,
                'is_enabled' => true,
            ],
            [
                'module' => 'accounting',
                'group' => 'journal_governance',
                'key' => 'gl_retained_earnings_account',
                'value' => '3120',
                'value_type' => 'string',
                'default_value' => '3120',
                'description' => 'General Ledger balance sheet account for Retained Earnings (3120 - जगेडा तथा नाफा नोक्सान).',
                'validation_rules' => 'required|string|max:10',
                'sort_order' => 60,
                'is_enabled' => true,
            ],

            // ==========================================
            // 6. HRM SETTINGS
            // ==========================================
            // ==========================================
            // Group: Workforce (Nepal Labour Act 2074)
            // ==========================================
            [
                'module' => 'hrm',
                'group' => 'workforce',
                'key' => 'standard_weekly_hours',
                'value' => '48.00',
                'value_type' => 'decimal',
                'default_value' => '48.00',
                'description' => 'Standard statutory full-time working hours per week under Nepal Labour Act 2074 (48.00 hrs).',
                'validation_rules' => 'required|numeric|min:10|max:60',
                'sort_order' => 10,
                'is_enabled' => true,
            ],
            [
                'module' => 'hrm',
                'group' => 'workforce',
                'key' => 'standard_daily_hours',
                'value' => '8.00',
                'value_type' => 'decimal',
                'default_value' => '8.00',
                'description' => 'Standard daily working hours threshold before overtime accrual triggers (8.00 hrs).',
                'validation_rules' => 'required|numeric|min:1|max:24',
                'sort_order' => 20,
                'is_enabled' => true,
            ],
            [
                'module' => 'hrm',
                'group' => 'workforce',
                'key' => 'employee_id_prefix',
                'value' => 'EMP-',
                'value_type' => 'string',
                'default_value' => 'EMP-',
                'description' => 'Prefix assigned to employee personnel files (e.g. EMP-0001).',
                'validation_rules' => 'required|string|max:10',
                'sort_order' => 30,
                'is_enabled' => true,
            ],
            [
                'module' => 'hrm',
                'group' => 'workforce',
                'key' => 'document_expiry_alert_days',
                'value' => '30',
                'value_type' => 'integer',
                'default_value' => '30',
                'description' => 'Lead time in days for alerts on expiring contracts and employment agreements.',
                'validation_rules' => 'required|integer|min:1|max:365',
                'sort_order' => 40,
                'is_enabled' => true,
            ],

            // Group: Leave & Holidays (Nepal Statutory Standards)
            [
                'module' => 'hrm',
                'group' => 'leaves',
                'key' => 'annual_home_leave_days',
                'value' => '18.00',
                'value_type' => 'decimal',
                'default_value' => '18.00',
                'description' => 'Statutory paid home leave per working year (1 day per 20 working days under Nepal Labour Act).',
                'validation_rules' => 'required|numeric|min:0|max:50',
                'sort_order' => 10,
                'is_enabled' => true,
            ],
            [
                'module' => 'hrm',
                'group' => 'leaves',
                'key' => 'annual_sick_leave_days',
                'value' => '12.00',
                'value_type' => 'decimal',
                'default_value' => '12.00',
                'description' => 'Statutory fully paid sick leave entitlement per year (12 days under Nepal Labour Act).',
                'validation_rules' => 'required|numeric|min:0|max:30',
                'sort_order' => 20,
                'is_enabled' => true,
            ],
            [
                'module' => 'hrm',
                'group' => 'leaves',
                'key' => 'annual_festival_leave_days',
                'value' => '13.00',
                'value_type' => 'decimal',
                'default_value' => '13.00',
                'description' => 'Statutory public & festival paid holidays per year in Nepal.',
                'validation_rules' => 'required|numeric|min:0|max:30',
                'sort_order' => 30,
                'is_enabled' => true,
            ],
            [
                'module' => 'hrm',
                'group' => 'leaves',
                'key' => 'dashain_festival_allowance_months',
                'value' => '1.00',
                'value_type' => 'decimal',
                'default_value' => '1.00',
                'description' => 'Statutory annual Dashain Festival bonus allowance (1 month basic salary).',
                'validation_rules' => 'required|numeric|min:0|max:2',
                'sort_order' => 40,
                'is_enabled' => true,
            ],

            // Group: Payroll & Nepal Statutory Contributions (SSF & IRD TDS)
            [
                'module' => 'hrm',
                'group' => 'payroll',
                'key' => 'ssf_employee_percentage',
                'value' => '11.00',
                'value_type' => 'decimal',
                'default_value' => '11.00',
                'description' => 'Social Security Fund (SSF) Nepal employee deduction percentage (11%).',
                'validation_rules' => 'required|numeric|min:0|max:20',
                'sort_order' => 10,
                'is_enabled' => true,
            ],
            [
                'module' => 'hrm',
                'group' => 'payroll',
                'key' => 'ssf_employer_percentage',
                'value' => '20.00',
                'value_type' => 'decimal',
                'default_value' => '20.00',
                'description' => 'Social Security Fund (SSF) Nepal employer contribution percentage (20%).',
                'validation_rules' => 'required|numeric|min:0|max:30',
                'sort_order' => 20,
                'is_enabled' => true,
            ],
            [
                'module' => 'hrm',
                'group' => 'payroll',
                'key' => 'default_tds_tax_rate_percentage',
                'value' => '1.00',
                'value_type' => 'decimal',
                'default_value' => '1.00',
                'description' => 'Nepal Inland Revenue Department (IRD) basic Social Security Tax / TDS baseline rate (1%).',
                'validation_rules' => 'required|numeric|min:0|max:40',
                'sort_order' => 30,
                'is_enabled' => true,
            ],
            [
                'module' => 'hrm',
                'group' => 'payroll',
                'key' => 'overtime_multiplier',
                'value' => '1.50',
                'value_type' => 'decimal',
                'default_value' => '1.50',
                'description' => 'Wage multiplier applied to basic rate for overtime hours worked (1.5x under Nepal Labour Act).',
                'validation_rules' => 'required|numeric|min:1.0|max:3.0',
                'sort_order' => 40,
                'is_enabled' => true,
            ],
            [
                'module' => 'hrm',
                'group' => 'payroll',
                'key' => 'require_timesheet_approval',
                'value' => '1',
                'value_type' => 'boolean',
                'default_value' => '1',
                'description' => 'Require departmental manager sign-off on timesheets before payroll execution.',
                'validation_rules' => 'required|boolean',
                'sort_order' => 50,
                'is_enabled' => true,
            ],
            [
                'module' => 'hrm',
                'group' => 'payroll',
                'key' => 'auto_post_payroll_to_accounting',
                'value' => '1',
                'value_type' => 'boolean',
                'default_value' => '1',
                'description' => 'Automatically post balanced double-entry accounting journal vouchers upon payroll approval.',
                'validation_rules' => 'required|boolean',
                'sort_order' => 60,
                'is_enabled' => true,
            ],

            // Group: Absence & Expenses
            [
                'module' => 'hrm',
                'group' => 'absence',
                'key' => 'sick_leave_medical_cert_days',
                'value' => '3',
                'value_type' => 'integer',
                'default_value' => '3',
                'description' => 'Consecutive sick days allowed before registered doctor medical certificate is required.',
                'validation_rules' => 'required|integer|min:1|max:14',
                'sort_order' => 10,
                'is_enabled' => true,
            ],
            [
                'module' => 'hrm',
                'group' => 'expenses',
                'key' => 'expense_claim_prefix',
                'value' => 'EXP-',
                'value_type' => 'string',
                'default_value' => 'EXP-',
                'description' => 'Prefix assigned to sequential employee expense claim vouchers (e.g. EXP-2026-0001).',
                'validation_rules' => 'required|string|max:10',
                'sort_order' => 10,
                'is_enabled' => true,
            ],

            // ==========================================
            // 7. CRM SETTINGS
            // ==========================================
            [
                'module' => 'crm',
                'group' => 'customers',
                'key' => 'customer_number_prefix',
                'value' => 'CUST-',
                'value_type' => 'string',
                'default_value' => 'CUST-',
                'description' => 'Identification prefix for registered clients.',
                'validation_rules' => 'required|string|max:10',
                'sort_order' => 10,
                'is_enabled' => true,
            ],
            [
                'module' => 'crm',
                'group' => 'customers',
                'key' => 'duplicate_detection_strategy',
                'value' => 'email_and_phone',
                'value_type' => 'select',
                'default_value' => 'email_and_phone',
                'description' => 'Unique matching criteria for customer account deduplication.',
                'validation_rules' => 'required|in:email_only,email_and_phone',
                'options' => ['email_only' => 'Match Email Address Only', 'email_and_phone' => 'Match Email or Telephone Number'],
                'sort_order' => 20,
                'is_enabled' => true,
            ],

            // ==========================================
            // 8. SHIPPING & DELIVERY SETTINGS (Nepal Only)
            // ==========================================
            [
                'module' => 'shipping',
                'group' => 'rates_thresholds',
                'key' => 'enable_free_shipping',
                'value' => '1',
                'value_type' => 'boolean',
                'default_value' => '1',
                'description' => 'Master switch enabling complimentary shipping promotions when cart subtotal meets threshold.',
                'validation_rules' => 'required|boolean',
                'sort_order' => 5,
                'is_enabled' => true,
            ],
            [
                'module' => 'shipping',
                'group' => 'rates_thresholds',
                'key' => 'free_shipping_threshold_npr',
                'value' => '5000.00',
                'value_type' => 'currency',
                'default_value' => '5000.00',
                'description' => 'Cart subtotal in NPR required for complimentary Kathmandu Valley shipping.',
                'validation_rules' => 'required|numeric|min:0',
                'sort_order' => 10,
                'is_enabled' => true,
            ],
            [
                'module' => 'shipping',
                'group' => 'rates_thresholds',
                'key' => 'free_shipping_calculation_mode',
                'value' => 'subtotal_after_discount',
                'value_type' => 'select',
                'default_value' => 'subtotal_after_discount',
                'description' => 'Determines whether free shipping threshold is evaluated before or after applying promotional coupons.',
                'validation_rules' => 'required|in:subtotal_after_discount,subtotal_before_discount',
                'options' => [
                    'subtotal_after_discount' => 'Net Subtotal (After Coupons & Discounts)',
                    'subtotal_before_discount' => 'Gross Subtotal (Before Coupons & Discounts)'
                ],
                'sort_order' => 20,
                'is_enabled' => true,
            ],
            [
                'module' => 'shipping',
                'group' => 'rates_thresholds',
                'key' => 'shipping_valley_flat_rate',
                'value' => '100.00',
                'value_type' => 'currency',
                'default_value' => '100.00',
                'description' => 'Flat delivery fee in NPR for Kathmandu Valley destinations.',
                'validation_rules' => 'required|numeric|min:0',
                'sort_order' => 30,
                'is_enabled' => true,
            ],
            [
                'module' => 'shipping',
                'group' => 'rates_thresholds',
                'key' => 'shipping_outside_valley_flat_rate',
                'value' => '150.00',
                'value_type' => 'currency',
                'default_value' => '150.00',
                'description' => 'Flat courier fee in NPR for destinations outside Kathmandu Valley.',
                'validation_rules' => 'required|numeric|min:0',
                'sort_order' => 40,
                'is_enabled' => true,
            ],
            [
                'module' => 'shipping',
                'group' => 'logistics',
                'key' => 'default_shipping_carrier',
                'value' => 'Pathao',
                'value_type' => 'select',
                'default_value' => 'Pathao',
                'description' => 'Primary courier partner for delivery dispatches in Nepal.',
                'validation_rules' => 'required|in:Pathao,NCM,Showroom Pickup',
                'options' => [
                    'Pathao' => 'Pathao Logistics (Valley & Fast Track)',
                    'NCM' => 'Nepal Can Move (Nationwide Courier)',
                    'Showroom Pickup' => 'Kathmandu Showroom Store Pickup'
                ],
                'sort_order' => 10,
                'is_enabled' => true,
            ],
            [
                'module' => 'shipping',
                'group' => 'sla',
                'key' => 'standard_delivery_days_min',
                'value' => '1',
                'value_type' => 'integer',
                'default_value' => '1',
                'description' => 'Minimum promised delivery window in business days.',
                'validation_rules' => 'required|integer|min:0|max:14',
                'sort_order' => 10,
                'is_enabled' => true,
            ],
            [
                'module' => 'shipping',
                'group' => 'sla',
                'key' => 'standard_delivery_days_max',
                'value' => '4',
                'value_type' => 'integer',
                'default_value' => '4',
                'description' => 'Maximum promised delivery window in business days for nationwide courier.',
                'validation_rules' => 'required|integer|min:1|max:30',
                'sort_order' => 20,
                'is_enabled' => true,
            ],
            [
                'module' => 'shipping',
                'group' => 'fulfillment_returns',
                'key' => 'return_shipping_covered_by',
                'value' => 'customer',
                'value_type' => 'select',
                'default_value' => 'customer',
                'description' => 'Policy for return courier charges on customer-initiated exchanges.',
                'validation_rules' => 'required|in:customer,store,defects_only',
                'options' => [
                    'customer' => 'Customer Pays (Deducted from Refund Total)',
                    'store' => 'Complimentary Return Shipping (Store Absorbs)',
                    'defects_only' => 'Customer Pays Unless Defective'
                ],
                'sort_order' => 50,
                'is_enabled' => true,
            ],
            [
                'module' => 'shipping',
                'group' => 'fulfillment_returns',
                'key' => 'return_shipping_fee_npr',
                'value' => '150.00',
                'value_type' => 'currency',
                'default_value' => '150.00',
                'description' => 'Standard return courier fee deduction in NPR.',
                'validation_rules' => 'required|numeric|min:0',
                'sort_order' => 60,
                'is_enabled' => true,
            ],
            [
                'module' => 'shipping',
                'group' => 'governance',
                'key' => 'require_tracking_number_on_dispatch',
                'value' => '1',
                'value_type' => 'boolean',
                'default_value' => '1',
                'description' => 'Enforces parcel tracking number entry prior to advancing orders to Shipped status.',
                'validation_rules' => 'required|boolean',
                'sort_order' => 70,
                'is_enabled' => true,
            ],
            [
                'module' => 'shipping',
                'group' => 'governance',
                'key' => 'failed_delivery_action',
                'value' => 'return_to_warehouse',
                'value_type' => 'select',
                'default_value' => 'return_to_warehouse',
                'description' => 'Automated stock workflow executed when courier reports abandoned or undeliverable shipment.',
                'validation_rules' => 'required|in:return_to_warehouse,mark_lost,contact_courier',
                'options' => [
                    'return_to_warehouse' => 'Restock to Warehouse & Cancel Order',
                    'mark_lost' => 'Mark as Lost in Transit',
                    'contact_courier' => 'Hold for Manual Investigation'
                ],
                'sort_order' => 80,
                'is_enabled' => true,
            ],

            // ==========================================
            // 9. PAYMENTS SETTINGS (Nepal Gateways & NPR)
            // ==========================================
            [
                'module' => 'payments',
                'group' => 'gateways',
                'key' => 'cod_enabled',
                'value' => '1',
                'value_type' => 'boolean',
                'default_value' => '1',
                'description' => 'Cash on Delivery (COD) payment option (Kathmandu Valley only).',
                'validation_rules' => 'required|boolean',
                'sort_order' => 10,
                'is_enabled' => true,
            ],
            [
                'module' => 'payments',
                'group' => 'gateways',
                'key' => 'connectips_enabled',
                'value' => '1',
                'value_type' => 'boolean',
                'default_value' => '1',
                'description' => 'Enable connectIPS direct bank transfer payment gateway.',
                'validation_rules' => 'required|boolean',
                'sort_order' => 20,
                'is_enabled' => true,
            ],
            [
                'module' => 'payments',
                'group' => 'gateways',
                'key' => 'esewa_enabled',
                'value' => '1',
                'value_type' => 'boolean',
                'default_value' => '1',
                'description' => 'Enable eSewa wallet and QR payment processing.',
                'validation_rules' => 'required|boolean',
                'sort_order' => 30,
                'is_enabled' => true,
            ],
            [
                'module' => 'payments',
                'group' => 'gateways',
                'key' => 'khalti_enabled',
                'value' => '1',
                'value_type' => 'boolean',
                'default_value' => '1',
                'description' => 'Enable Khalti digital wallet gateway.',
                'validation_rules' => 'required|boolean',
                'sort_order' => 40,
                'is_enabled' => true,
            ],
            [
                'module' => 'payments',
                'group' => 'credentials',
                'key' => 'esewa_secret_key',
                'value' => '8gBm/:&EnhH.1/q(',
                'value_type' => 'password',
                'default_value' => '8gBm/:&EnhH.1/q(',
                'description' => 'eSewa merchant HMAC secret key for verifying payment hashes.',
                'validation_rules' => 'required|string',
                'is_sensitive' => true,
                'sort_order' => 50,
                'is_enabled' => true,
            ],
            [
                'module' => 'payments',
                'group' => 'limits_currencies',
                'key' => 'min_checkout_amount_npr',
                'value' => '100.00',
                'value_type' => 'currency',
                'default_value' => '100.00',
                'description' => 'Minimum allowable order value in NPR to proceed to checkout.',
                'validation_rules' => 'required|numeric|min:0',
                'sort_order' => 10,
                'is_enabled' => true,
            ],
            [
                'module' => 'payments',
                'group' => 'limits_currencies',
                'key' => 'default_currency',
                'value' => 'NPR',
                'value_type' => 'string',
                'default_value' => 'NPR',
                'description' => 'Authoritative business currency (Nepalese Rupee).',
                'validation_rules' => 'required|string',
                'sort_order' => 20,
                'is_enabled' => true,
            ],
            [
                'module' => 'payments',
                'group' => 'limits_currencies',
                'key' => 'accepted_currencies',
                'value' => json_encode(['NPR']),
                'value_type' => 'json',
                'default_value' => json_encode(['NPR']),
                'description' => 'List of accepted currencies in store operations.',
                'validation_rules' => 'required',
                'sort_order' => 30,
                'is_enabled' => true,
            ],

            // ==========================================
            // 10. NOTIFICATION SETTINGS
            // ==========================================
            [
                'module' => 'notifications',
                'group' => 'channels',
                'key' => 'email_notifications_enabled',
                'value' => '1',
                'value_type' => 'boolean',
                'default_value' => '1',
                'description' => 'Global master switch for automated email communications.',
                'validation_rules' => 'required|boolean',
                'sort_order' => 10,
                'is_enabled' => true,
            ],
            [
                'module' => 'notifications',
                'group' => 'channels',
                'key' => 'admin_alert_email',
                'value' => 'info@laijau.com',
                'value_type' => 'string',
                'default_value' => 'info@laijau.com',
                'description' => 'Primary inbox destination for high-priority operational system alerts.',
                'validation_rules' => 'required|email',
                'sort_order' => 20,
                'is_enabled' => true,
            ],
            [
                'module' => 'notifications',
                'group' => 'event_triggers',
                'key' => 'notify_on_low_stock',
                'value' => '1',
                'value_type' => 'boolean',
                'default_value' => '1',
                'description' => 'Dispatch alert immediately when an item breaches reorder threshold.',
                'validation_rules' => 'required|boolean',
                'sort_order' => 10,
                'is_enabled' => true,
            ],
            [
                'module' => 'notifications',
                'group' => 'event_triggers',
                'key' => 'notify_on_new_order',
                'value' => '1',
                'value_type' => 'boolean',
                'default_value' => '1',
                'description' => 'Notify warehouse fulfillment team on confirmed e-commerce orders.',
                'validation_rules' => 'required|boolean',
                'sort_order' => 20,
                'is_enabled' => true,
            ],
            [
                'module' => 'notifications',
                'group' => 'event_triggers',
                'key' => 'notify_on_failed_payment',
                'value' => '1',
                'value_type' => 'boolean',
                'default_value' => '1',
                'description' => 'Send operational alert when a customer checkout payment attempt fails.',
                'validation_rules' => 'required|boolean',
                'sort_order' => 20,
                'is_enabled' => true,
            ],

            // ==========================================
            // 11. MARKETING & CONTENT SETTINGS
            // ==========================================
            [
                'module' => 'marketing',
                'group' => 'seo_metadata',
                'key' => 'default_meta_title',
                'value' => 'Laijau — Quality Footwear, Clothing & Fashion in Nepal',
                'value_type' => 'string',
                'default_value' => 'Laijau — Quality Footwear, Clothing & Fashion in Nepal',
                'description' => 'Default HTML title tag for search engines.',
                'validation_rules' => 'required|string|max:100',
                'sort_order' => 10,
                'is_enabled' => true,
                'is_public' => true,
            ],
            [
                'module' => 'marketing',
                'group' => 'seo_metadata',
                'key' => 'default_meta_description',
                'value' => 'Shop quality shoes, sneakers, boots, clothing, and accessories at Laijau. Kathmandu Valley delivery and nationwide courier across all 77 districts.',
                'value_type' => 'text',
                'default_value' => 'Shop quality shoes, sneakers, boots, clothing, and accessories at Laijau. Kathmandu Valley delivery and nationwide courier across all 77 districts.',
                'description' => 'Default meta description tag indexed by search engines.',
                'validation_rules' => 'required|string|max:300',
                'sort_order' => 20,
                'is_enabled' => true,
                'is_public' => true,
            ],
            [
                'module' => 'marketing',
                'group' => 'tracking_pixels',
                'key' => 'google_analytics_id',
                'value' => 'G-LAIJAU',
                'value_type' => 'string',
                'default_value' => 'G-LAIJAU',
                'description' => 'Google Analytics 4 Measurement ID.',
                'validation_rules' => 'nullable|string|max:30',
                'sort_order' => 10,
                'is_enabled' => true,
            ],

            // ==========================================
            // 12. ANALYTICS SETTINGS
            // ==========================================
            [
                'module' => 'analytics',
                'group' => 'tracking',
                'key' => 'enable_analytics_tracking',
                'value' => '1',
                'value_type' => 'boolean',
                'default_value' => '1',
                'description' => 'Record storefront visitor interactions, searches, and conversion events.',
                'validation_rules' => 'required|boolean',
                'sort_order' => 10,
                'is_enabled' => true,
            ],
            [
                'module' => 'analytics',
                'group' => 'data_retention',
                'key' => 'data_retention_days',
                'value' => '730',
                'value_type' => 'duration',
                'default_value' => '730',
                'description' => 'Days to retain historical analytics before automated GDPR purging.',
                'validation_rules' => 'required|integer|min:30|max:1825',
                'sort_order' => 10,
                'is_enabled' => true,
            ],

            // ==========================================
            // 13. SYSTEM SETTINGS
            // ==========================================
            [
                'module' => 'system',
                'group' => 'platform_maintenance',
                'key' => 'maintenance_mode',
                'value' => '0',
                'value_type' => 'boolean',
                'default_value' => '0',
                'description' => 'Put customer storefront in maintenance hold while allowing admin access.',
                'validation_rules' => 'required|boolean',
                'sort_order' => 10,
                'is_enabled' => true,
            ],
            [
                'module' => 'system',
                'group' => 'platform_maintenance',
                'key' => 'maintenance_message',
                'value' => 'Laijau is currently updating our catalog. Please visit us shortly.',
                'value_type' => 'text',
                'default_value' => 'Laijau is currently updating our catalog. Please visit us shortly.',
                'description' => 'Customer-facing notice displayed during scheduled maintenance.',
                'validation_rules' => 'required|string|max:500',
                'sort_order' => 20,
                'is_enabled' => true,
            ],
            [
                'module' => 'system',
                'group' => 'security_api',
                'key' => 'session_lifetime_minutes',
                'value' => '120',
                'value_type' => 'duration',
                'default_value' => '120',
                'description' => 'Inactivity duration before administrative sessions expire.',
                'validation_rules' => 'required|integer|min:15|max:1440',
                'sort_order' => 10,
                'is_enabled' => true,
            ],
            [
                'module' => 'system',
                'group' => 'security_api',
                'key' => 'api_rate_limit_per_minute',
                'value' => '120',
                'value_type' => 'integer',
                'default_value' => '120',
                'description' => 'Maximum requests allowed per minute per IP address on public endpoints.',
                'validation_rules' => 'required|integer|min:10|max:1000',
                'sort_order' => 20,
                'is_enabled' => true,
            ],
            [
                'module' => 'system',
                'group' => 'security_api',
                'key' => 'audit_log_retention_days',
                'value' => '365',
                'value_type' => 'duration',
                'default_value' => '365',
                'description' => 'Days to preserve immutable setting mutation audit logs.',
                'validation_rules' => 'required|integer|min:30|max:3650',
                'sort_order' => 30,
                'is_enabled' => true,
            ],
            [
                'module' => 'system',
                'group' => 'security_api',
                'key' => 'password_reset_timeout_minutes',
                'value' => '60',
                'value_type' => 'duration',
                'default_value' => '60',
                'description' => 'Time window in minutes before a customer password reset token expires.',
                'validation_rules' => 'required|integer|min:10|max:1440',
                'sort_order' => 40,
                'is_enabled' => true,
            ],
        ];

        // 3. Insert or update settings idempotently
        foreach ($settings as $settingData) {
            $isSensitive = $settingData['is_sensitive'] ?? false;
            $preparedVal = ModuleSetting::prepareValueForStorage(
                $settingData['value'],
                $settingData['value_type'],
                $isSensitive
            );

            ModuleSetting::updateOrCreate(
                [
                    'module' => $settingData['module'],
                    'key' => $settingData['key'],
                ],
                [
                    'group' => $settingData['group'],
                    'value' => $preparedVal,
                    'value_type' => $settingData['value_type'],
                    'default_value' => $settingData['default_value'],
                    'description' => $settingData['description'] ?? null,
                    'validation_rules' => $settingData['validation_rules'] ?? null,
                    'options' => $settingData['options'] ?? null,
                    'sort_order' => $settingData['sort_order'] ?? 0,
                    'is_enabled' => $settingData['is_enabled'] ?? true,
                    'is_public' => $settingData['is_public'] ?? false,
                    'is_sensitive' => $isSensitive,
                    'is_editable' => $settingData['is_editable'] ?? true,
                ]
            );
        }
    }
}
